
#
# Copyright 2012 Stijn De Weirdt
# 
# This file is part of HanythingOnDemand,
# originally created by the HPC team of the University of Ghent (http://ugent.be/hpc).
#
from vsc import fancylogger


import os, sys, re

class Job:
    def __init__(self, options):
        self.log = fancylogger.getLogger(self.__class__.__name__)

        self.options = options

        self.nrnodes = None
        self.corespernode = None

        self.script = None

        self.type = None

        self.modules = []

        self.run_in_cwd = True


    def submit(self):
        """Submit this job"""
        if self.script is None:
            self.generate_script()

        self.log.debug("Going to submit jobscript %s" % self.script)
        self.type.submit(self.script)
        self.log.debug("Submission returned jobid %s" % self.type.jobid)

    def generate_script(self):
        """Build the submit script"""
        script = ["#!/bin/bash", "## Generated by HOD"]
        script += self.generate_script_header()

        script += self.generate_environment()

        if self.run_in_cwd:
            script.append("cd $%s" % self.type.vars['cwd'])

        script += self.generate_exe()

        self.log.debug("Generated script %s" % script)
        self.script = "\n".join(script + [''])

    def generate_environment(self):
        """Generate the environment to start the job"""
        script_env = self.generate_modules()
        script_env += self.generate_extra_environment()

        return script_env

    def generate_extra_environment(self):
        """Generate other environment parameters to start the job"""
        extra_env = []
        self.log.debug("Nothing to add.")
        return extra_env

    def generate_exe(self):
        """The actual executable"""
        self.log.debug("generate_exe not implemented")

        return ['## Not implemented']

    def generate_script_header(self):
        """Create the job arguments. Retrun as header (if used)"""
        hdr = self.type.header()
        self.log.debug("Generated header %s" % hdr)

        return hdr

    def generate_modules(self):
        """Generate the module statements. Returns a list. Elements that are string or 1 long are assumed to be load requests"""
        allmods = []
        for md in self.modules:
            if type(md) in (str,):
                allmods.append(['load', md])
            elif type(md) in (list, tuple):
                if len(md) == 1:
                    allmods.append(['load', md[0]])
                else:
                    allmods.append(md)
            else:
                self.log.error("Unknown module type %s (%s)" % (type(md), md))

        self.log.debug("Going to generate string for modules %s" % allmods)
        return ['module %s' % (" ".join(md)) for md in allmods]

